Repository weareinreach/InReach, pull requests merged in 2022-12, with the labels that each got.

#111 feat: large & small buttons
  .deepsource.toml
  packages/ui/.storybook/i18next.ts
  packages/ui/.storybook/main.ts
  packages/ui/components/core/Button.stories.tsx
  packages/ui/theme/common.ts
  packages/ui/theme/functions/buttonVariants.ts
Labels: automerge, new-feature, 📦 ui

#128 refactor: switch icon set to FA
  apps/app/lib/generators/socialMedia.ts
  apps/app/public/locales/en/common.json
  apps/app/src/data/socialMedia.json
  packages/ui/components/core/Button.stories.tsx
  packages/ui/components/layout/Footer.tsx
  packages/ui/components/layout/UserMenu.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: refactor, 📦 app, 📦 ui

#127 feat: add link component
  packages/ui/components/core/Link.stories.tsx
  packages/ui/components/core/Link.tsx
Labels: automerge, new-feature, 📦 ui

#126 feat: social media button stories
  packages/ui/components/core/SocialMediaIcon.tsx
  packages/ui/components/core/SocialMediaIconButton.stories.tsx
Labels: automerge, new-feature, 📦 ui

#130 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/xx-XX/attribute.json
  apps/app/public/locales/xx-XX/common.json
  apps/app/public/locales/xx-XX/country.json
  apps/app/public/locales/xx-XX/footer.json
  apps/app/public/locales/xx-XX/gov-dist.json
  apps/app/public/locales/xx-XX/nav.json
  apps/app/public/locales/xx-XX/services.json
  apps/app/public/locales/xx-XX/socialMedia.json
  apps/app/public/locales/xx-XX/user.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'
