Repository weareinreach/InReach, pull requests merged in 2023-06, with the labels that each got.

#513 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/common.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/xx-XX/common.json
  apps/app/public/locales/xx-XX/landingPage.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#523 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/landingPage.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#525 release: beta2.1
  apps/app/package.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/src/pages/suggest.tsx
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/package.json
  packages/eslint-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#535 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
  apps/app/public/locales/xx-XX/attribute.json
  apps/app/public/locales/xx-XX/common.json
  apps/app/public/locales/xx-XX/country.json
  apps/app/public/locales/xx-XX/gov-dist.json
  apps/app/public/locales/xx-XX/landingPage.json
  apps/app/public/locales/xx-XX/phone-type.json
  apps/app/public/locales/xx-XX/services.json
  apps/app/public/locales/xx-XX/suggestOrg.json
  apps/app/public/locales/xx-XX/user.json
Labels: automerge, translations, kodiak: merge.method = 'squash'

#537 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#538 fix: pre-launch tweaks
  apps/app/nextjs-routes.d.ts
  apps/app/package.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/landingPage.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/account/index.tsx
  apps/app/src/pages/index.tsx
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/pages/saved/index.tsx
  apps/app/src/pages/search/[...params]/index.tsx
  apps/app/src/pages/support/index.tsx
  packages/api/router/user.ts
  packages/api/schemas/attributeSupplements/accessInstructions.ts
  packages/config/package.json
  packages/ui/components/core/AntiHateMessage.tsx
  packages/ui/components/core/Breadcrumb.tsx
  packages/ui/components/core/MobileNav.tsx
  packages/ui/components/core/SearchBox.tsx
  packages/ui/components/sections/Contact.tsx
  packages/ui/components/sections/Hero.tsx
  packages/ui/components/sections/Navbar.tsx
  packages/ui/components/sections/SearchResultSidebar.tsx
  packages/ui/components/sections/SuggestOrg/index.tsx
  packages/ui/components/sections/VisitCard.tsx
  packages/ui/modals/ForgotPassword.tsx
  packages/ui/modals/MoreFilter.tsx
  packages/ui/modals/QuickPromotion.tsx
  packages/ui/modals/Service.tsx
  packages/ui/modals/ServiceFilter.tsx
  packages/ui/modals/SignUp/fields.tsx
  packages/ui/modals/SignUp/index.tsx
  packages/ui/package.json
  packages/ui/theme/variants/Text.ts
  packages/ui/theme/variants/index.ts
  pnpm-lock.yaml
Labels: bugfix, automerge, 📦 app, 📦 api, 📦 ui, 📦 config

#539 release: THE BIG ONE.
  apps/app/nextjs-routes.d.ts
  apps/app/package.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/landingPage.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/account/index.tsx
  apps/app/src/pages/index.tsx
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/pages/saved/index.tsx
  apps/app/src/pages/search/[...params]/index.tsx
  apps/app/src/pages/support/index.tsx
  packages/api/router/user.ts
  packages/api/schemas/attributeSupplements/accessInstructions.ts
  packages/config/package.json
  packages/ui/components/core/AntiHateMessage.tsx
  packages/ui/components/core/Breadcrumb.tsx
  packages/ui/components/core/MobileNav.tsx
  packages/ui/components/core/SearchBox.tsx
  packages/ui/components/sections/Contact.tsx
  packages/ui/components/sections/Hero.tsx
  packages/ui/components/sections/Navbar.tsx
  packages/ui/components/sections/SearchResultSidebar.tsx
  packages/ui/components/sections/SuggestOrg/index.tsx
  packages/ui/components/sections/VisitCard.tsx
  packages/ui/modals/ForgotPassword.tsx
  packages/ui/modals/MoreFilter.tsx
  packages/ui/modals/QuickPromotion.tsx
  packages/ui/modals/Service.tsx
  packages/ui/modals/ServiceFilter.tsx
  packages/ui/modals/SignUp/fields.tsx
  packages/ui/modals/SignUp/index.tsx
  packages/ui/package.json
  packages/ui/theme/variants/Text.ts
  packages/ui/theme/variants/index.ts
  pnpm-lock.yaml
Labels: automerge, release

#540 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/common.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
  apps/app/public/locales/xx-XX/common.json
  apps/app/public/locales/xx-XX/landingPage.json
Labels: automerge, translations, kodiak: merge.method = 'squash'

#541 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/ru/common.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/xx-XX/common.json
  apps/app/public/locales/xx-XX/landingPage.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#546 fix: post-launch issues
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/landingPage.json
  apps/app/public/locales/en/services.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/admin/quicklink/email.tsx
  apps/app/src/pages/admin/quicklink/phone.tsx
  apps/app/src/pages/admin/quicklink/services.tsx
  apps/app/src/pages/index.tsx
  packages/api/router/service/queries.ts
  packages/db/generated/allAttributes.ts
  packages/db/generated/attributeCategory.ts
  packages/db/generated/attributesByCategory.ts
  packages/db/generated/userRole.ts
  packages/db/prisma/data-migrations/2023-06-07_update-tag.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/seed/downloadData.ts
  packages/db/turbo.json
  packages/ui/modals/GenericContent.tsx
  packages/ui/modals/PrivacyStatement.tsx
Labels: bugfix, automerge, 📦 app, 📦 db, 📦 api, 📦 ui

#544 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
  apps/app/public/locales/xx-XX/attribute.json
  apps/app/public/locales/xx-XX/country.json
  apps/app/public/locales/xx-XX/gov-dist.json
  apps/app/public/locales/xx-XX/phone-type.json
  apps/app/public/locales/xx-XX/services.json
  apps/app/public/locales/xx-XX/suggestOrg.json
  apps/app/public/locales/xx-XX/user.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#548 release: 2023-06-07
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/landingPage.json
  apps/app/public/locales/en/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
  apps/app/public/locales/xx-XX/attribute.json
  apps/app/public/locales/xx-XX/country.json
  apps/app/public/locales/xx-XX/gov-dist.json
  apps/app/public/locales/xx-XX/phone-type.json
  apps/app/public/locales/xx-XX/services.json
  apps/app/public/locales/xx-XX/suggestOrg.json
  apps/app/public/locales/xx-XX/user.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/admin/quicklink/email.tsx
  apps/app/src/pages/admin/quicklink/phone.tsx
  apps/app/src/pages/admin/quicklink/services.tsx
  apps/app/src/pages/index.tsx
  packages/api/router/service/queries.ts
  packages/db/generated/allAttributes.ts
  packages/db/generated/attributeCategory.ts
  packages/db/generated/attributesByCategory.ts
  packages/db/generated/userRole.ts
  packages/db/prisma/data-migrations/2023-06-07_update-tag.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/seed/downloadData.ts
  packages/db/turbo.json
  packages/ui/modals/GenericContent.tsx
  packages/ui/modals/PrivacyStatement.tsx
Labels: automerge, release

#551 fix: quicklink query
  apps/app/src/pages/admin/quicklink/services.tsx
  packages/api/router/quicklink.ts
Labels: bugfix, automerge

#554 fix: signup/login/reset pw flow
  .github/workflows/crowdin.yml
  apps/app/src/pages/index.tsx
  packages/api/router/quicklink.ts
  packages/api/schemas/create/user.ts
  packages/auth/lib/cognitoClient.ts
  packages/auth/lib/userLogin.ts
  packages/aws-user-migrate/Makefile
  packages/aws-user-migrate/build.sh
  packages/aws-user-migrate/package.json
  packages/aws-user-migrate/src/getUser.ts
  packages/aws-user-migrate/template.yaml
  packages/aws-user-migrate/tsconfig.json
  packages/db/prisma/migrations/20230608224620_user_signup_data_field/migration.sql
  packages/db/prisma/schema.prisma
  packages/ui/components/core/Button.tsx
  packages/ui/lib/getTrpcMock.ts
  packages/ui/lib/trpcResponse.ts
  packages/ui/modals/ForgotPassword.tsx
  packages/ui/modals/Login.tsx
  packages/ui/modals/SignUp/index.stories.tsx
  packages/ui/modals/SignUp/index.tsx
Labels: bugfix, automerge, 📦 app, 📦 db, 📦 api, 📦 ui, 📦 auth, 📦 aws-user-migrate

#555 fix: modal sizing on mobile
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ClaimOrg.tsx
  packages/ui/modals/CreateNewList.tsx
  packages/ui/modals/DeleteModal.tsx
  packages/ui/modals/ForgotPassword.tsx
  packages/ui/modals/Login.tsx
  packages/ui/modals/ResetPassword.tsx
  packages/ui/modals/Review.tsx
Labels: bugfix, automerge, 📦 ui

#557 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/ru/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#558 release: 2023-06-08
  .github/workflows/chromatic.yml
  .github/workflows/crowdin.yml
  .github/workflows/pr-labels.yml
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/ru/common.json
  apps/app/src/pages/index.tsx
  packages/api/router/quicklink.ts
  packages/api/schemas/create/user.ts
  packages/auth/lib/cognitoClient.ts
  packages/auth/lib/userLogin.ts
  packages/aws-user-migrate/Makefile
  packages/aws-user-migrate/build.sh
  packages/aws-user-migrate/package.json
  packages/aws-user-migrate/src/getUser.ts
  packages/aws-user-migrate/template.yaml
  packages/aws-user-migrate/tsconfig.json
  packages/db/prisma/migrations/20230608224620_user_signup_data_field/migration.sql
  packages/db/prisma/schema.prisma
  packages/ui/components/core/Button.tsx
  packages/ui/lib/getTrpcMock.ts
  packages/ui/lib/trpcResponse.ts
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ClaimOrg.tsx
  packages/ui/modals/CreateNewList.tsx
  packages/ui/modals/DeleteModal.tsx
  packages/ui/modals/ForgotPassword.tsx
  packages/ui/modals/Login.tsx
  packages/ui/modals/ResetPassword.tsx
  packages/ui/modals/Review.tsx
  packages/ui/modals/SignUp/index.stories.tsx
  packages/ui/modals/SignUp/index.tsx
Labels: automerge, release

#549 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
Labels: automerge, translations, kodiak: merge.method = 'squash'

#560 fix: update search card to filter for duplicate cities
  packages/db/prisma/data-migrations/2023-06-08_trim-city-whitespace/data.json
  packages/db/prisma/data-migrations/2023-06-08_trim-city-whitespace/index.ts
  packages/db/prisma/data-migrations/index.ts
  packages/ui/components/core/SearchResultCard.tsx
  packages/ui/mockData/searchResults.ts
Labels: bugfix, automerge, 📦 db, 📦 ui

#559 fix: added center prop to Text and Title of the QuickPromotion modal
  packages/ui/modals/QuickPromotion.tsx
Labels: bugfix, automerge, 📦 ui

#553 fix: update text on 'Accessibility Statement'
  apps/app/public/locales/en/common.json
Labels: bugfix, automerge, 📦 app

#564 fix: unpublish duplicate websites
  packages/db/prisma/data-migrations/2023-06-09_duplicate-websites/data.json
  packages/db/prisma/data-migrations/2023-06-09_duplicate-websites/index.ts
  packages/db/prisma/data-migrations/index.ts
Labels: bugfix, automerge, 📦 db

#563 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#565 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#566 release: 2023-06-09
  .github/workflows/cache.yml
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  .github/workflows/crowdin.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/ar/country.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/ar/services.json
  apps/app/public/locales/en/attribute.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/fr/country.json
  apps/app/public/locales/fr/landingPage.json
  apps/app/public/locales/fr/services.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/ru/common.json
  apps/app/public/locales/ru/country.json
  apps/app/public/locales/ru/landingPage.json
  apps/app/public/locales/ru/services.json
  apps/app/src/pages/account/index.tsx
  apps/app/src/pages/index.tsx
  apps/app/src/pages/saved/index.tsx
  apps/app/src/pages/support/index.tsx
  docker/docker-compose.yml
  packages/db/generated/allAttributes.ts
  packages/db/generated/serviceCategory.ts
  packages/db/prisma/data-migrations/2023-06-08_trim-city-whitespace/data.json
  packages/db/prisma/data-migrations/2023-06-08_trim-city-whitespace/index.ts
  packages/db/prisma/data-migrations/2023-06-08_update-law-practice-opts.ts
  packages/db/prisma/data-migrations/2023-06-09_duplicate-websites/data.json
  packages/db/prisma/data-migrations/2023-06-09_duplicate-websites/index.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/seed/data/09-attributes.ts
  packages/ui/components/core/SearchResultCard.tsx
  packages/ui/mockData/searchResults.ts
  packages/ui/modals/QuickPromotion.tsx
Labels: automerge, release

#573 fix: Update 'no reviews' text
  apps/app/public/locales/en/common.json
Labels: bugfix, automerge, 📦 app

#575 fix: check for mobile or tablet to allow print
  packages/ui/components/core/ActionButtons.tsx
Labels: bugfix, automerge, 📦 ui

#577 fix: add "isPublic" filter to locations
  packages/api/schemas/selects/org.ts
Labels: bugfix, automerge, 📦 api

#579 release: 2023-06-12
  .github/workflows/lock.yml
  apps/app/package.json
  apps/app/public/locales/en/common.json
  apps/app/src/pages/org/[slug]/index.tsx
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/api/schemas/selects/org.ts
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/package.json
  packages/eslint-config/package.json
  packages/ui/components/core/ActionButtons.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#570 fix: user survey
  apps/app/public/locales/en/attribute.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/user.json
  packages/api/schemas/create/user.ts
  packages/db/generated/allAttributes.ts
  packages/db/generated/attributesByCategory.ts
  packages/db/generated/namespaces.ts
  packages/db/generated/userType.ts
  packages/db/lib/generators/namespaces.ts
  packages/db/prisma/common.ts
  packages/db/prisma/data-migrations/2023-06-12_survey-options.ts
  packages/db/prisma/data-migrations/2023-06-13_user-type.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/prisma/migrations/20230612212856_active_flags/migration.sql
  packages/db/prisma/migrations/20230612222045_add_fields_for_other/migration.sql
  packages/db/prisma/schema.prisma
  packages/ui/.storybook/preview.tsx
  packages/ui/components/core/Button.tsx
  packages/ui/components/data-portal/AddressDrawer.tsx
  packages/ui/components/data-portal/EmailTableDrawer.tsx
  packages/ui/components/data-portal/PhoneTableDrawer.tsx
  packages/ui/mockData/surveyOptions.ts
  packages/ui/modals/AccountVerified.stories.tsx
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/SignUp/context.ts
  packages/ui/modals/SignUp/fields.tsx
  packages/ui/modals/SignUp/index.tsx
  packages/ui/modals/UserSurvey/context.ts
  packages/ui/modals/UserSurvey/fields.tsx
  packages/ui/modals/UserSurvey/index.tsx
  packages/ui/modals/dataPortal/PhoneEmail/fields.tsx
  packages/ui/theme/variants/Anchor.ts
  packages/ui/theme/variants/Button.ts
  packages/ui/theme/variants/index.ts
Labels: bugfix, automerge, refactor, 📦 app, 📦 db, 📦 api, 📦 ui

#578 fix: check for mobile before displaying description
  packages/ui/components/core/SearchResultCard.tsx
Labels: bugfix, automerge, 📦 ui

#585 release: 2023-06-13
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  .github/workflows/crowdin.yml
  apps/app/package.json
  apps/app/public/locales/en/attribute.json
  apps/app/public/locales/en/common.json
  apps/app/public/locales/en/user.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/api/schemas/create/user.ts
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/generated/allAttributes.ts
  packages/db/generated/attributesByCategory.ts
  packages/db/generated/namespaces.ts
  packages/db/generated/userType.ts
  packages/db/lib/generators/namespaces.ts
  packages/db/package.json
  packages/db/prisma/common.ts
  packages/db/prisma/data-migrations/2023-06-12_survey-options.ts
  packages/db/prisma/data-migrations/2023-06-13_user-type.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/prisma/migrations/20230612212856_active_flags/migration.sql
  packages/db/prisma/migrations/20230612222045_add_fields_for_other/migration.sql
  packages/db/prisma/schema.prisma
  packages/eslint-config/package.json
  packages/ui/.storybook/preview.tsx
  packages/ui/components/core/Badge.tsx
  packages/ui/components/core/Button.tsx
  packages/ui/components/core/SearchResultCard.tsx
  packages/ui/components/data-portal/AddressDrawer.tsx
  packages/ui/components/data-portal/EmailTableDrawer.tsx
  packages/ui/components/data-portal/PhoneTableDrawer.tsx
  packages/ui/mockData/surveyOptions.ts
  packages/ui/modals/AccountVerified.stories.tsx
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/SignUp/context.ts
  packages/ui/modals/SignUp/fields.tsx
  packages/ui/modals/SignUp/index.tsx
  packages/ui/modals/UserSurvey/context.ts
  packages/ui/modals/UserSurvey/fields.tsx
  packages/ui/modals/UserSurvey/index.tsx
  packages/ui/modals/dataPortal/PhoneEmail/fields.tsx
  packages/ui/package.json
  packages/ui/theme/variants/Anchor.ts
  packages/ui/theme/variants/Button.ts
  packages/ui/theme/variants/index.ts
  pnpm-lock.yaml
Labels: automerge, release

#590 chore: add Sentry monitoring
  .gitignore
  InReach.code-workspace
  apps/app/.gitignore
  apps/app/next.config.mjs
  apps/app/package.json
  apps/app/sentry.client.config.ts
  apps/app/sentry.edge.config.ts
  apps/app/sentry.server.config.ts
  apps/app/src/pages/api/panel.ts
  apps/app/src/pages/api/trpc-playground.ts
  apps/app/src/pages/api/trpc/[trpc].ts
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/utils/api.ts
  apps/app/turbo.json
  apps/web/package.json
  docs/package.json
  package.json
  packages/api/package.json
  packages/api/trpc/client.ts
  packages/auth/lib/cognitoClient.ts
  packages/auth/lib/cognitoJwt.ts
  packages/auth/lib/index.ts
  packages/auth/lib/logger.ts
  packages/auth/next-auth/auth-options.ts
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/package.json
  packages/env/index.ts
  packages/env/package.json
  packages/env/tsconfig.json
  packages/ui/lib/trpcClient.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: bugfix, dependencies, automerge, 📦 app, 📦 db, 📦 web, 📦 api, 📦 ui, 📦 auth, 📦 config, 📦 aws-user-migrate, 📦 aws-messaging, 📦 aws-cache, 📦 env

#591 release: 2023-06-14
  .gitignore
  InReach.code-workspace
  apps/app/.gitignore
  apps/app/next.config.mjs
  apps/app/package.json
  apps/app/sentry.client.config.ts
  apps/app/sentry.edge.config.ts
  apps/app/sentry.server.config.ts
  apps/app/src/pages/api/panel.ts
  apps/app/src/pages/api/trpc-playground.ts
  apps/app/src/pages/api/trpc/[trpc].ts
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/utils/api.ts
  apps/app/turbo.json
  apps/web/package.json
  docs/package.json
  package.json
  packages/api/package.json
  packages/api/trpc/client.ts
  packages/auth/lib/cognitoClient.ts
  packages/auth/lib/cognitoJwt.ts
  packages/auth/lib/index.ts
  packages/auth/lib/logger.ts
  packages/auth/next-auth/auth-options.ts
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/package.json
  packages/env/index.ts
  packages/env/package.json
  packages/env/tsconfig.json
  packages/eslint-config/package.json
  packages/ui/lib/trpcClient.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#595 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/af/gov-dist.json
  apps/app/public/locales/ar/gov-dist.json
  apps/app/public/locales/es/gov-dist.json
  apps/app/public/locales/fa/gov-dist.json
  apps/app/public/locales/fr/gov-dist.json
  apps/app/public/locales/hi/gov-dist.json
  apps/app/public/locales/ht/gov-dist.json
  apps/app/public/locales/ja/gov-dist.json
  apps/app/public/locales/ko/gov-dist.json
  apps/app/public/locales/pl/gov-dist.json
  apps/app/public/locales/ps/gov-dist.json
  apps/app/public/locales/pt/gov-dist.json
  apps/app/public/locales/ru/gov-dist.json
  apps/app/public/locales/sw/gov-dist.json
  apps/app/public/locales/tl/gov-dist.json
  apps/app/public/locales/uk/gov-dist.json
  apps/app/public/locales/zh/gov-dist.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#607 release 2023-06-16b
  apps/app/public/locales/en/common.json
Labels: automerge, release

#606 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/af/common.json
  apps/app/public/locales/fa/common.json
  apps/app/public/locales/hi/common.json
  apps/app/public/locales/ht/common.json
  apps/app/public/locales/ja/common.json
  apps/app/public/locales/ko/common.json
  apps/app/public/locales/pl/attribute.json
  apps/app/public/locales/pl/common.json
  apps/app/public/locales/ps/common.json
  apps/app/public/locales/pt/common.json
  apps/app/public/locales/sw/common.json
  apps/app/public/locales/tl/common.json
  apps/app/public/locales/uk/common.json
  apps/app/public/locales/zh/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#582 feat: Added tooltip for Claimed and Unclaimed badges
  apps/app/public/locales/en/common.json
  packages/ui/components/core/Badge.tsx
Labels: bugfix, automerge, 📦 app, 📦 ui, 📦 auth

#617 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/af/common.json
  apps/app/public/locales/ar/common.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/fa/common.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/hi/common.json
  apps/app/public/locales/ht/common.json
  apps/app/public/locales/ja/common.json
  apps/app/public/locales/ko/common.json
  apps/app/public/locales/pl/common.json
  apps/app/public/locales/ps/common.json
  apps/app/public/locales/pt/common.json
  apps/app/public/locales/ru/common.json
  apps/app/public/locales/sw/common.json
  apps/app/public/locales/tl/common.json
  apps/app/public/locales/uk/common.json
  apps/app/public/locales/zh/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#627 fix: tooltip & auto modals
  packages/eslint-config/base.js
  packages/ui/components/core/Badge.tsx
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ClaimOrg.tsx
  packages/ui/modals/ResetPassword.tsx
Labels: bugfix, automerge, 📦 ui, 📦 eslint-config

#628 release: 2023-06-22
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  apps/app/package.json
  apps/app/src/pages/org/[slug]/index.tsx
  apps/web/package.json
  apps/web/turbo.json
  apps/web/vercel.json
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/aws-user-migrate/package.json
  packages/db/package.json
  packages/env/index.ts
  packages/env/package.json
  packages/eslint-config/base.js
  packages/eslint-config/package.json
  packages/ui/.storybook/main.ts
  packages/ui/components/core/Badge.tsx
  packages/ui/components/data-portal/AddressDrawer.tsx
  packages/ui/components/data-portal/EmailTableDrawer.tsx
  packages/ui/components/data-portal/PhoneTableDrawer.tsx
  packages/ui/components/sections/SearchResultSidebar.tsx
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ClaimOrg.tsx
  packages/ui/modals/ResetPassword.tsx
  packages/ui/modals/dataPortal/PhoneEmail/fields.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#630 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/gov-dist.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/es/user.json
Labels: automerge, translations, kodiak: merge.method = 'squash'

#637 fix: account verify/reset password modals
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ResetPassword.tsx
Labels: bugfix, automerge, 📦 ui

#633 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/es/suggestOrg.json
  apps/app/public/locales/es/user.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#638 release: 2023-06-27
  apps/app/package.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/es/country.json
  apps/app/public/locales/es/landingPage.json
  apps/app/public/locales/es/services.json
  apps/app/public/locales/es/suggestOrg.json
  apps/app/public/locales/es/user.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/aws-cache/package.json
  packages/aws-messaging/package.json
  packages/aws-user-migrate/package.json
  packages/config/package.json
  packages/db/package.json
  packages/env/package.json
  packages/eslint-config/package.json
  packages/ui/modals/AccountVerified.tsx
  packages/ui/modals/ResetPassword.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release
