Repository weareinreach/InReach, pull requests merged in 2024-03, with the labels that each got.

#1134 fix(search): Repeat city searching now working
  packages/ui/components/core/SearchBox.tsx
Labels: bugfix, priority-low, automerge, 📦 app, 📦 ui, kodiak: merge.method = 'squash'

#1133 fix(search): "Clear" button working
  apps/app/src/pages/search/[...params]/index.tsx
  packages/ui/components/core/SearchBox.tsx
Labels: bugfix, priority-low, automerge, 📦 app, 📦 ui, kodiak: merge.method = 'squash'

#1128 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ht/attribute.json
  apps/app/public/locales/ht/common.json
  apps/app/public/locales/ht/country.json
  apps/app/public/locales/ht/gov-dist.json
  apps/app/public/locales/ht/landingPage.json
  apps/app/public/locales/ht/phone-type.json
  apps/app/public/locales/ht/services.json
  apps/app/public/locales/ht/suggestOrg.json
  apps/app/public/locales/ht/user.json
  apps/app/public/locales/ja/country.json
  apps/app/public/locales/ja/gov-dist.json
  apps/app/public/locales/pt/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#1144 release: 2024-03-07
  .github/workflows/codeql.yml
  .github/workflows/crowdin.yml
  .github/workflows/nextjs_bundle_analysis.yml
  .github/workflows/njsscan.yml
  apps/app/package.json
  apps/app/public/locales/ht/attribute.json
  apps/app/public/locales/ht/common.json
  apps/app/public/locales/ht/country.json
  apps/app/public/locales/ht/gov-dist.json
  apps/app/public/locales/ht/landingPage.json
  apps/app/public/locales/ht/phone-type.json
  apps/app/public/locales/ht/services.json
  apps/app/public/locales/ht/suggestOrg.json
  apps/app/public/locales/ht/user.json
  apps/app/public/locales/ja/country.json
  apps/app/public/locales/ja/gov-dist.json
  apps/app/public/locales/pt/common.json
  apps/app/src/pages/search/[...params]/index.tsx
  apps/web/package.json
  docker/docker-control.ts
  lambdas/cognito-messaging/package.json
  lambdas/cognito-user-migrate/package.json
  package.json
  packages/analytics/package.json
  packages/api/package.json
  packages/api/router/location/query.forLocationPage.handler.ts
  packages/api/router/location/query.forVisitCard.handler.ts
  packages/api/router/organization/query.forOrgPage.handler.ts
  packages/auth/package.json
  packages/config/package.json
  packages/crowdin/package.json
  packages/db/package.json
  packages/env/package.json
  packages/eslint-config/package.json
  packages/ui/components/core/SearchBox.tsx
  packages/ui/components/sections/ListingBasicInfo.tsx
  packages/ui/icon/iconList.ts
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#1145 release: 2024-03-07b
  apps/app/package.json
  apps/web/package.json
  lambdas/cognito-messaging/package.json
  lambdas/cognito-user-migrate/package.json
  package.json
  packages/api/package.json
  packages/api/router/location/query.forLocationPageEdits.handler.ts
  packages/api/router/organization/query.forOrgPageEdits.handler.ts
  packages/auth/package.json
  packages/config/package.json
  packages/crowdin/package.json
  packages/db/package.json
  packages/eslint-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release

#1147 chore: data migration (urls & misc)
  packages/db/.gitignore
  packages/db/prisma/data-migrations/2024-03-08_update-alerts-and-org-urls/index.ts
  packages/db/prisma/data-migrations/2024-03-11_hide-locations.ts
  packages/db/prisma/data-migrations/index.ts
Labels: automerge, maintenance, 📦 db, kodiak: merge.method = 'squash'

#1142 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/ht/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#1149 release: 2024-03-12
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  .github/workflows/crowdin.yml
  .github/workflows/njsscan.yml
  apps/app/next-i18next.config.mjs
  apps/app/next.config.mjs
  apps/app/package.json
  apps/app/public/locales/ar/landingPage.json
  apps/app/public/locales/es/common.json
  apps/app/public/locales/ht/common.json
  apps/web/package.json
  lambdas/cognito-messaging/package.json
  lambdas/cognito-user-migrate/package.json
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/config/package.json
  packages/crowdin/package.json
  packages/db/.gitignore
  packages/db/package.json
  packages/db/prisma/data-migrations/2024-03-08_update-alerts-and-org-urls/index.ts
  packages/db/prisma/data-migrations/2024-03-11_hide-locations.ts
  packages/db/prisma/data-migrations/index.ts
  packages/db/tsconfig.json
  packages/env/package.json
  packages/eslint-config/package.json
  packages/ui/components/core/Donate/index.tsx
  packages/ui/package.json
  packages/ui/theme/colors.ts
  packages/ui/theme/common.tsx
  packages/ui/types/mantine.d.ts
  pnpm-lock.yaml
Labels: automerge, release

#1152 fix: search state navigation carryover
  apps/app/src/pages/org/[slug]/[orgLocationId]/edit/[orgServiceId].tsx
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/providers/index.tsx
  packages/api/router/organization/query.searchDistance.handler.ts
  packages/ui/components/core/Badge/Group.tsx
  packages/ui/components/core/Badge/Leader.tsx
  packages/ui/components/core/Badge/National.tsx
  packages/ui/components/core/Badge/styles.ts
  packages/ui/components/core/SearchBox.tsx
  packages/ui/components/core/SearchResultCard.tsx
  packages/ui/modals/MoreFilter.tsx
  packages/ui/modals/ServiceFilter/index.tsx
Labels: bugfix, automerge, 📦 app, 📦 api, 📦 ui, kodiak: merge.method = 'squash'

#1154 fix: modal placement/hydration errors
  apps/app/next-i18next.config.mjs
  apps/app/public/locales/en/common.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  packages/ui/components/core/Breadcrumb.tsx
  packages/ui/components/core/UserAvatar.tsx
  packages/ui/components/core/UserMenu.tsx
  packages/ui/components/sections/Footer.tsx
  packages/ui/components/sections/Navbar.tsx
  packages/ui/modals/Service/index.tsx
  packages/ui/theme/common.tsx
Labels: bugfix, automerge, 📦 app, 📦 ui, kodiak: merge.method = 'squash'

#1155 release: 2024-03-13
  apps/app/lib/generators/translationKeys.ts
  apps/app/next-i18next.config.mjs
  apps/app/package.json
  apps/app/public/locales/en/common.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/org/[slug]/[orgLocationId]/edit/[orgServiceId].tsx
  apps/app/src/pages/org/[slug]/[orgLocationId]/index.tsx
  apps/app/src/pages/org/[slug]/index.tsx
  apps/app/src/providers/index.tsx
  apps/web/package.json
  lambdas/cognito-messaging/package.json
  lambdas/cognito-user-migrate/package.json
  package.json
  packages/analytics/package.json
  packages/api/package.json
  packages/api/router/organization/query.searchDistance.handler.ts
  packages/auth/package.json
  packages/config/package.json
  packages/db/package.json
  packages/env/package.json
  packages/eslint-config/package.json
  packages/ui/components/core/Badge/Community.tsx
  packages/ui/components/core/Badge/Group.tsx
  packages/ui/components/core/Badge/Leader.tsx
  packages/ui/components/core/Badge/National.tsx
  packages/ui/components/core/Badge/styles.ts
  packages/ui/components/core/Breadcrumb.tsx
  packages/ui/components/core/SearchBox.tsx
  packages/ui/components/core/SearchResultCard.tsx
  packages/ui/components/core/UserAvatar.tsx
  packages/ui/components/core/UserMenu.tsx
  packages/ui/components/data-portal/InlineTextInput.tsx
  packages/ui/components/sections/Footer.tsx
  packages/ui/components/sections/Navbar.tsx
  packages/ui/modals/MoreFilter.tsx
  packages/ui/modals/Service/index.tsx
  packages/ui/modals/ServiceFilter/index.tsx
  packages/ui/package.json
  packages/ui/theme/common.tsx
  pnpm-lock.yaml
  turbo.json
Labels: automerge, release

#1156 chore: data migration - access links & misc
  packages/db/prisma/data-migrations/2024-03-15_update-dead-links/!schemas.ts
  packages/db/prisma/data-migrations/2024-03-15_update-dead-links/index.ts
  packages/db/prisma/data-migrations/index.ts
Labels: automerge, maintenance, 📦 db, kodiak: merge.method = 'squash'

#1159 chore: Update Marker type from Google Maps API
  packages/ui/components/core/GoogleMap.stories.tsx
  packages/ui/hooks/useGoogleMapMarker.tsx
  packages/ui/providers/GoogleMaps.tsx
Labels: automerge, maintenance, 📦 ui, kodiak: merge.method = 'squash'

#1160 fix: i18n loading/lang change
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/search/[...params]/index.tsx
Labels: bugfix, automerge, 📦 app, kodiak: merge.method = 'squash'

#1162 release: 2024-03-18
  .github/workflows/codeql.yml
  .github/workflows/nextjs_bundle_analysis.yml
  .github/workflows/njsscan.yml
  apps/app/package.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/search/[...params]/index.tsx
  apps/web/package.json
  lambdas/cognito-messaging/package.json
  lambdas/cognito-user-migrate/package.json
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/config/package.json
  packages/db/package.json
  packages/db/prisma/data-migrations/2024-03-15_update-dead-links/!schemas.ts
  packages/db/prisma/data-migrations/2024-03-15_update-dead-links/index.ts
  packages/db/prisma/data-migrations/index.ts
  packages/eslint-config/package.json
  packages/ui/components/core/GoogleMap.stories.tsx
  packages/ui/components/data-portal/MultiSelectPopover/hook-form.tsx
  packages/ui/components/data-portal/MultiSelectPopover/index.tsx
  packages/ui/hooks/useGoogleMapMarker.tsx
  packages/ui/modals/MoreFilter.tsx
  packages/ui/modals/ServiceFilter/index.tsx
  packages/ui/other/DataViewer.tsx
  packages/ui/package.json
  packages/ui/providers/GoogleMaps.tsx
  pnpm-lock.yaml
Labels: automerge, release

#1164 chore: misc updates/cleanup
  apps/app/lib/generators/translationKeys.ts
  apps/app/public/locales/en/attribute.json
  packages/api/package.json
  packages/api/schemas/create/organization.ts
  packages/api/schemas/nestedOps.ts
  packages/db/package.json
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/ui/.storybook/preview.tsx
  packages/ui/.swcrc
  packages/ui/components/core/Badge/index.tsx
  packages/ui/components/core/Donate/index.stories.tsx
  packages/ui/lib/trpcResponse.ts
  packages/ui/package.json
  packages/ui/providers/SearchState.tsx
  packages/ui/public/mockServiceWorker.js
  pnpm-lock.yaml
Labels: automerge, maintenance, 📦 app, 📦 db, 📦 api, 📦 ui, 📦 eslint-config, kodiak: merge.method = 'squash'

#1161 chore(i18n): Updated translations from Crowdin
  apps/app/public/locales/af/attribute.json
  apps/app/public/locales/ar/attribute.json
  apps/app/public/locales/de-DE/attribute.json
  apps/app/public/locales/es/attribute.json
  apps/app/public/locales/fa/attribute.json
  apps/app/public/locales/fr/attribute.json
  apps/app/public/locales/fr/common.json
  apps/app/public/locales/hi/attribute.json
  apps/app/public/locales/ht/attribute.json
  apps/app/public/locales/ht/common.json
  apps/app/public/locales/ht/country.json
  apps/app/public/locales/ja/attribute.json
  apps/app/public/locales/ja/common.json
  apps/app/public/locales/ja/country.json
  apps/app/public/locales/ja/services.json
  apps/app/public/locales/ja/user.json
  apps/app/public/locales/ko/attribute.json
  apps/app/public/locales/pl/attribute.json
  apps/app/public/locales/ps/attribute.json
  apps/app/public/locales/pt/attribute.json
  apps/app/public/locales/ru/attribute.json
  apps/app/public/locales/sw/attribute.json
  apps/app/public/locales/sw/common.json
  apps/app/public/locales/tl/attribute.json
  apps/app/public/locales/tr-TR/attribute.json
  apps/app/public/locales/uk/attribute.json
  apps/app/public/locales/zh/attribute.json
  apps/app/public/locales/zh/common.json
Labels: automerge, translations, 📦 app, kodiak: merge.method = 'squash'

#1169 fix: i18n loading/service name display
  apps/app/next-i18next.config.mjs
  apps/app/sentry.server.config.ts
  packages/api/router/service/query.forServiceInfoCard.handler.ts
  packages/ui/components/sections/ListingBasicInfo.tsx
  packages/ui/components/sections/ServicesInfo.tsx
  packages/util/logger/index.ts
Labels: bugfix, automerge, 📦 app, 📦 api, 📦 ui, kodiak: merge.method = 'squash', 📦 util

#1171 refactor: use simplified Badge component
  packages/ui/components/core/Badge/Verified.tsx
  packages/ui/components/core/Badge/index.stories.tsx
  packages/ui/components/core/Badge/index.tsx
  packages/ui/components/core/UserReview.tsx
  packages/ui/components/data-portal/ServiceEditDrawer.tsx
  packages/ui/components/data-portal/ServicesDrawer.tsx
  packages/ui/components/sections/CrisisSupport/InternationalCard.tsx
  packages/ui/components/sections/CrisisSupport/NationalCard.tsx
  packages/ui/components/sections/ListingBasicInfo.tsx
  packages/ui/components/sections/LocationCard.tsx
  packages/ui/components/sections/ServicesInfo.tsx
  packages/ui/components/sections/VisitCard.tsx
  packages/ui/modals/Service/index.tsx
  packages/ui/modals/dataPortal/Attributes/index.tsx
Labels: automerge, refactor, 📦 ui, kodiak: merge.method = 'squash'

#1180 chore: sonarlint config
  .vscode/settings.json
  apps/app/.vscode/settings.json
  apps/web/.vscode/settings.json
  lambdas/.vscode/settings.json
  packages/analytics/.vscode/settings.json
  packages/api/.vscode/settings.json
  packages/auth/.vscode/settings.json
  packages/config/.vscode/settings.json
  packages/crowdin/.vscode/settings.json
  packages/db/.vscode/settings.json
  packages/env/.vscode/settings.json
  packages/eslint-config/.vscode/settings.json
  packages/ui/.vscode/settings.json
  packages/util/.vscode/settings.json
Labels: automerge, maintenance, 📦 app, 📦 db, 📦 web, 📦 api, 📦 ui, 📦 auth, 📦 config, 📦 eslint-config, kodiak: merge.method = 'squash', 📦 env, 📦 util, 📦 crowdin, 📦 analytics

#1183 fix(app): Updated margins
  packages/ui/components/core/SearchBox.tsx
Labels: bugfix, automerge, 📦 ui, kodiak: merge.method = 'squash'

#1184 feat(app): Search on enter
  packages/ui/components/core/SearchBox.tsx
Labels: automerge, new-feature, 📦 ui, kodiak: merge.method = 'squash'

#1185 fix: convert email to lowercase
  packages/api/router/user/mutation.adminCreate.schema.ts
  packages/api/router/user/mutation.confirmAccount.handler.ts
  packages/api/router/user/mutation.create.schema.ts
  packages/api/router/user/mutation.deleteAccount.handler.ts
  packages/api/router/user/mutation.forgotPassword.schema.ts
  packages/api/router/user/mutation.resetPassword.handler.ts
  packages/auth/lib/changePassword.ts
  packages/auth/lib/cognitoJwt.ts
  packages/auth/lib/confirmAccount.ts
  packages/auth/lib/createUser.ts
  packages/auth/lib/deleteAccount.ts
  packages/auth/lib/forgotPassword.ts
  packages/auth/lib/genUserSession.ts
  packages/auth/lib/refreshSession.ts
  packages/auth/lib/resendCode.ts
  packages/auth/lib/resetPassword.ts
  packages/auth/lib/userLogin.ts
  packages/auth/providers/cognito.ts
Labels: bugfix, automerge, 📦 api, 📦 auth, kodiak: merge.method = 'squash'

#1188 chore: update legislative map url
  apps/app/src/pages/search/[...params]/index.tsx
Labels: automerge, maintenance, 📦 app, kodiak: merge.method = 'squash'

#1189 release: 2024-03-26
  apps/app/src/pages/search/[...params]/index.tsx
Labels: automerge, release

#1192 release: 2024-03-28
  .nvmrc
  apps/app/package.json
  apps/app/src/pages/_app.tsx
  apps/app/src/pages/_document.tsx
  apps/web/package.json
  package.json
  packages/analytics/package.json
  packages/api/package.json
  packages/auth/package.json
  packages/crowdin/package.json
  packages/db/package.json
  packages/eslint-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: automerge, release
